pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven {url  "https://repo1.maven.org/maven2/"}
        maven { url = "https://oss.sonatype.org/content/repositories/snapshots/" }
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {url  "https://repo1.maven.org/maven2/"}
        maven { url = "https://oss.sonatype.org/content/repositories/snapshots/" }

    }
}
//include ':androidp'
//include ':shadersNfilters'
//include ':mediaeffectswithopengles',
//include ':mediasdk'
//include ':aireminder'
//include ':testcode', ':camerax'//, ':preferencesample'
//include ':canvas'
//include ':opeglesgame'
//include  ':tutsopengles'
//include ':launchmode'
//include ':audioprocessing'
//include ':processbuilderex'
//include  ':camera2'
//include  ':verticaledittext', ':hijricalendar'
//include  ':camera'
//include ':webviewfeatures'
//include ':players'
//include ':retrosquashgame'
//include ':snake'
//include ':gameframework', ':testframework', ':mrnom'
//include ':mediaapi'
//include ':removeorientationtest'
//include ':ffmpegjni'
//include ':androidservices'
//include ':dagger2'
//include ':motionlayout'
//include ':flexbox'
//include ':buildflavours'
//include ':oldnavigation'
//include ':moshi'
//include ':pdf'
//include ':animation'
//include ':device'
//include ':appwidget'
//include ':bluetooth'
//include ':mediax'
//include ':widgets'
//include ':tencent-miniapp'
//include ':socketio'
//include ':fontfamily'
//include ':compose-animations'
//include ':javascriptengine'
//include ':flexlayout'
include ':sdk-hilt-dagger'
include ':sdk-hilt-dagger:sdk'
include ':sdk-hilt-dagger:hilt'
include ':sdk-hilt-dagger:integrated-app'
