/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_androvid_ffmpeg_Header */

#ifndef _Included_com_androvid_ffmpeg_Header
#define _Included_com_androvid_ffmpeg_Header
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_androvid_ffmpeg_Header
 * Method:    cancelAction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_androvid_ffmpeg_Header_cancelAction
  (JNIEnv *, jobject);

/*
 * Class:     com_androvid_ffmpeg_Header
 * Method:    getAVInfo
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_androvid_ffmpeg_Header_getAVInfo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_androvid_ffmpeg_Header
 * Method:    getProgress
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_androvid_ffmpeg_Header_getProgress
  (JNIEnv *, jobject);

/*
 * Class:     com_androvid_ffmpeg_Header
 * Method:    loadFFMPEGLibrary
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_androvid_ffmpeg_Header_loadFFMPEGLibrary
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_androvid_ffmpeg_Header
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_androvid_ffmpeg_Header_run
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_androvid_ffmpeg_Header
 * Method:    unloadFFMPEGLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_androvid_ffmpeg_Header_unloadFFMPEGLibrary
  (JNIEnv *, jobject);

/*
 * Class:     com_androvid_ffmpeg_Header
 * Method:    setAudioProgress
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_androvid_ffmpeg_Header_setAudioProgress
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
